"use strict"

module.exports = {
  url: "https://azraelsdomain.tech",
  title: "Domain of Azrael",
  tagline: "A Blog Dedicated To All Things Programming and Scripting!",
  copyright: "© 2019 Paul Castillo, All rights reserved",
  author: {
    name: "PAUL CASTILLO",
    bio:
      "Developer, Husband, Father, Drummer, Amateur Astronomer, Air Force Veteran",
    contacts: {
      reddit: "https://www.reddit.com/user/pcast01",
      linkedin: "https://www.linkedin.com/in/will-ward-65234a170/",
      github: "https://github.com/pcast01",
      stackoverflow: "https://stackoverflow.com/users/436108/paul",
      twitter: "https://twitter.com/pcast01",
      youtube: "https://www.youtube.com/user/pcast01",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 20,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 20,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "powershell",
      tech: "Powershell",
      name: "DiTerminal",
      size: 20,
      color: "blue",
    },
    {
      tag: "excel",
      tech: "Excel",
      name: "FaFileExcel",
      size: 20,
      color: "darkgreen",
    },
    {
      tag: "pi",
      tech: "Raspberry PI",
      name: "DiRasberryPi",
      size: 20,
      color: "maroon",
    },
    {
      tag: "net",
      tech: "C#",
      name: "DiNetmagazine",
      size: 20,
      color: "green",
    },
  ],
}
